organization:
  session_name: cctest
  
  # parent_idで親子関係を表現
  roles:
    - id: boss
      name: 森本部長
      role: 組織のリーダー
      parent_id: null  # トップレベル
      responsibilities:
        - タスクの受注
        - 全体の進捗管理
        - 納品物の最終確認
        - 成果物の納品
    
    - id: projectManager
      name: 野上課長
      role: タスクの管理および割り振り
      parent_id: boss
      responsibilities:
        - taskManagerに対してタスクの細分化や管理を依頼する
        - taskManagerから受け取ったタスクをdevManagerに依頼する
        - devManagerからの報告をtaskManagerに連携する
        - bossに対してタスクの進捗を報告する
    
    - id: taskManager
      name: 武田さん
      role: タスクの細分化や提案を行う
      parent_id: projectManager
      responsibilities:
        - projectManagerからの質問に回答する
        - projectManagerから受け取ったタスクを簡潔に細分化する
        - 必要に応じてタスクの提案を行う
        - 進捗報告を基にタスクの進捗管理を行う
        - タスクの進捗を確認し、必要に応じて修正依頼を出す
        - bossに対してタスクの進捗を報告する
    
    - id: devManager
      name: 上村さん
      role: アプリ開発の管理を行う
      parent_id: projectManager
      responsibilities:
        - projectManagerからアプリ開発関連のタスクを受け取る
        - 各developerにタスクの割り振りを行う
        - タスクが完了次第、projectManagerに進捗報告を行う
        - 追加のタスクが必要だと判断した場合はprojectManagerに提案する
    
    - id: reviewer
      name: 葭葉さん
      role: コードのレビューを行う
      parent_id: devManager
      responsibilities:
        - 各developerからコードのレビュー依頼を受け取る
        - コードのレビューを行う
        - レビュー結果をdeveloperに連携する
        - 必要に応じてコードの修正を依頼する
    
    - id: developer01
      name: 内田さん
      role: アプリの開発01
      parent_id:
        - devManager
        - reviewer
      responsibilities:
        - Linterを意識したコード開発を行う
        - テストのしやすさを意識したコード開発を行う
        - 性能を意識したコード開発を行う
        - 可読性の向上を意識したコード開発を行う
        - reviewer01に対してコードのレビュー依頼を行う
        - レビュ―結果をもとにコードの修正を行う
        - コードの修正が完了いたらtester01にテスト依頼を行う
        - テストが完了次第、tester01からのテスト結果をもとにコードの修正を行い、再度テスト依頼を行う
        - コードが完成したらdevManagerに進捗報告を行う
    
    - id: developer02
      name: 岡田さん
      role: アプリの開発02
      parent_id:
        - devManager
        - reviewer
      responsibilities:
        - Linterを意識したコード開発を行う
        - テストのしやすさを意識したコード開発を行う
        - 性能を意識したコード開発を行う
        - 可読性の向上を意識したコード開発を行う
        - reviewer01に対してコードのレビュー依頼を行う
        - レビュ―結果をもとにコードの修正を行う
        - コードの修正が完了いたらtester01にテスト依頼を行う
        - テストが完了次第、tester01からのテスト結果をもとにコードの修正を行い、再度テスト依頼を行う
        - コードが完成したらdevManagerに進捗報告を行う
    
    - id: tester01
      name: 久田さん
      role: テストの実施を行う
      parent_id: developer01
      responsibilities:
        - developer01からテスト依頼を受け取る
        - テストを実施する
        - テスト結果をdeveloper01に連携する
        - 必要に応じてテストの再実施を依頼する
        - テストが完了次第、developer01に進捗報告を行う
    
    - id: tester02
      name: 下吹越さん
      role: テストの実施を行う
      parent_id: developer02
      responsibilities:
        - developer02からテスト依頼を受け取る
        - テストを実施する
        - テスト結果をdeveloper02に連携する
        - 必要に応じてテストの再実施を依頼する
        - テストが完了次第、developer02に進捗報告を行う